name: Build APK for master

on:
  push:
    branches: master

jobs:
  apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/checkout_submodules

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build release APK
        run: |
          echo $KEYSTORE_FILE | base64 -d > app/build.keystore
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/app/build.keystore \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release/app-release.apk
